### PR TITLE
Add "WEIGHTS" option to ZINTERSTORE and ZUNIONSTORE

### PR DESCRIPTION
**Pull request by yurigorokhov**
This pull-request adds the ability to specify weights when performing a ZINTERSTORE and ZUNIONSTORE with 2 new commands: 

StoreUnionFromSortedSetsWithWeights
StoreIntersectFromSortedSetsWithWeights

Example:
ZINTERSTORE out 2 zset1 zset2 WEIGHTS 2 3

source: http://redis.io/commands/zinterstore

Goes together with: https://github.com/NServiceKit/NServiceKit/pull/43

### CODE REVIEW

**Comment by yurigorokhov** [comment]
@vdaron when you have a chance, mind taking a look at this one. Have been running this in production for a few weeks now.

**Comment by yurigorokhov** [comment]
@vdaron any chance you could look at this?

**Comment by vdaron** [comment]
Hi @yurigorokhov ,

Sorry for late answer, I've merge your changes. @mirthy, could you update nuget packages ?

**Comment by yurigorokhov** [comment]
Thanks a lot guys, excited to switch to the nuget package!

**Comment by coreycoto** [comment]
@mirthy, could help update the NuGet package? @yurigorokhov and I would love to switch over to it.

**Comment by mirthy** [comment]
Sorry about that, I'll take care of that now!

**Comment by mirthy** [comment]
@yurigorokhov @vdaron @coreycoto Pushed!  Sorry for the late response!!!!

**Comment by yurigorokhov** [comment]
@vdaron @mirthy @coreycoto thanks for the package update. But I just notice the interface changes weren't merged: https://github.com/NServiceKit/NServiceKit/pull/43

We may need to merge it and repeat the process. 

I had linked it in this pull-request. Is there a process you guys follow, so that these don't get missed. Let me know if I can make it clearer in the future.

**Comment by vdaron** [comment]
Sorry, my bad

**Comment by vdaron** [comment]
Branch has been merged @mirthy could you update nuget ... again...

sorry

**Comment by mirthy** [comment]
Sorry for the delay, building and updating everything now.

**Comment by mirthy** [comment]
Built and redeployed

**Review by ERITONS — COMMENTED** [review]
ok

**Pull request merged**
