### PR TITLE
ZADD with multiple values/scores

### PR DESCRIPTION
**Pull request by yurigorokhov**
I propose exposing a method that allows a batch ZADD:

ZADD key score1 value1 score2 value2 score3 value3 ...

### CODE REVIEW

**Comment by yurigorokhov** [comment]
@vdaron how does this look?

**Comment by vdaron** [comment]
Hi @yurigorokhov 

What do you think to use the "params" signature instead of List ?

```
public long AddRangeToSortedSetWithScores(string setId, params KeyValuePair<string, double>[] valuesWithScore)
```

instead of

```
public long AddRangeToSortedSetWithScores(string setId, List<KeyValuePair<string, double>> valuesWithScore)
```

It is just a suggestion,...

**Comment by yurigorokhov** [comment]
Hi @vdaron ,

Looking at the rest of the code base, it seems that "params" is often used when specifying keys (setIds), but List<> is used for values.  Which makes sense to me, since keys are likely to be a small set of hard-coded values specified manually, but values are more likely to be a large collection.

That is my opinion on it, let me know what you think. I'd be happy to add an overload as well.

**Comment by vdaron** [comment]
make sense

Thanks

Vincent.

**Pull request merged**
